#if !defined __VI_VAR_FRAME_TAG_H__ || defined VI_VAR_FRAME_MAKE_TAGS
#undef __VI_VAR_FRAME_TAG_H__
#define __VI_VAR_FRAME_TAG_H__
#include <map>

#ifdef VI_VAR_FRAME_MAKE_TAGS
	#define DEF_VI_VAR_FRAME_ENGINE std::map<int,CString> TAG_VI_FRAME; class _TAG_VI_FRAME
	#define DEF_VI_VAR_FRAME(x) TAG_VI_FRAME[x] =  _T("") _T(#x) _T("")
	#define DEF_VI_VAR_FRAME_START public: ~_TAG_VI_FRAME() {}; _TAG_VI_FRAME() {
	#define DEF_VI_VAR_FRAME_END ;}
	#define DEF_VI_VAR_FRAME_DONE _TAG_VI_FRAME gTAG_VI_FRAME;
#else
#define DEF_VI_VAR_FRAME_ENGINE extern std::map<int,CString> TAG_VI_FRAME; enum VI_VAR_FRAME_ENGINE
	#define DEF_VI_VAR_FRAME(x) x
	#define DEF_VI_VAR_FRAME_START __VI_INFO_START = 10000,
	#define DEF_VI_VAR_FRAME_END
	#define DEF_VI_VAR_FRAME_DONE

	enum SOUND_MODE { SNDM_OFF = 0, SNDM_HG = 1, SNDM_HR, SNDM_SR, SNDM_SG, SNDM_CG, SNDM_CR };
#endif


DEF_VI_VAR_FRAME_ENGINE
{
	DEF_VI_VAR_FRAME_START

	DEF_VI_VAR_FRAME( VI_INFO_START ),

	DEF_VI_VAR_FRAME(VI_INFO_CORE_ID),
	DEF_VI_VAR_FRAME(VI_INFO_CORE_MAX),
	DEF_VI_VAR_FRAME(VI_INFO_CORE_USE),

	DEF_VI_VAR_FRAME(VI_INFO_M_START),
	DEF_VI_VAR_FRAME(VI_INFO_M_PROGRESS),
	DEF_VI_VAR_FRAME(VI_INFO_M_PERIOD),
	DEF_VI_VAR_FRAME(VI_INFO_M_EXTERNAL),
	DEF_VI_VAR_FRAME(VI_INFO_M_M),
	DEF_VI_VAR_FRAME(VI_INFO_M_S),
	DEF_VI_VAR_FRAME(VI_INFO_M_PI),
	DEF_VI_VAR_FRAME(VI_INFO_M_BMIN),
	DEF_VI_VAR_FRAME(VI_INFO_M_CMIN),
	DEF_VI_VAR_FRAME(VI_INFO_M_BMAX),
	DEF_VI_VAR_FRAME(VI_INFO_M_CMAX),
	DEF_VI_VAR_FRAME(VI_INFO_M_OPEN),
	DEF_VI_VAR_FRAME(VI_INFO_M_END),

	DEF_VI_VAR_FRAME(VI_INFO_CORREL),

	DEF_VI_VAR_FRAME(VI_INFO_DISABLE_AUDIO),

	DEF_VI_VAR_FRAME( VI_INFO_GRAPH_SHOW ),
	DEF_VI_VAR_FRAME( VI_INFO_GRAPH_SHOW2 ),
	DEF_VI_VAR_FRAME( VI_INFO_GRAPH_MIN ),
	DEF_VI_VAR_FRAME( VI_INFO_GRAPH_MAX ),
	DEF_VI_VAR_FRAME( VI_INFO_GRAPH_DIF ),
	DEF_VI_VAR_FRAME(VI_INFO_GRAPH_AUTO),
	DEF_VI_VAR_FRAME( VI_INFO_GRAPH_FLT_LF_AVG ),
	DEF_VI_VAR_FRAME( VI_INFO_GRAPH_FLT_LF ),
	DEF_VI_VAR_FRAME( VI_INFO_GRAPH_FLT_HF ),

	DEF_VI_VAR_FRAME( VI_INFO_GRAPH_PERIOD ),
	DEF_VI_VAR_FRAME( VI_INFO_GRAPH_DIF_PERIOD ),
	DEF_VI_VAR_FRAME( VI_INFO_GRAPH_HIST_PERIOD ),
	DEF_VI_VAR_FRAME(VI_INFO_GRAPH_HIDE_ALL),

	DEF_VI_VAR_FRAME( VI_INFO_STAT_RATE1 ),
	DEF_VI_VAR_FRAME( VI_INFO_STAT_RATE2 ),
	DEF_VI_VAR_FRAME( VI_INFO_STAT_RATE1V ),
	DEF_VI_VAR_FRAME( VI_INFO_STAT_RATE2V ),
	DEF_VI_VAR_FRAME( VI_INFO_STAT_LEVEL ),
	DEF_VI_VAR_FRAME(VI_INFO_STAT_VAR),
	DEF_VI_VAR_FRAME( VI_INFO_STAT_CALC ),
	DEF_VI_VAR_FRAME( VI_INFO_STAT_CMIN ),
	DEF_VI_VAR_FRAME( VI_INFO_STAT_CMAX ),
	DEF_VI_VAR_FRAME( VI_INFO_STAT_BMIN ),
	DEF_VI_VAR_FRAME( VI_INFO_STAT_BMAX ),

	DEF_VI_VAR_FRAME( VI_INFO_HIST_F_ID_R ),
	DEF_VI_VAR_FRAME( VI_INFO_HIST_F_ID_G ),

	DEF_VI_VAR_FRAME( VI_INFO_HIST_F_PERIOD ),
	DEF_VI_VAR_FRAME( VI_INFO_HIST_A_PERIOD ),
	DEF_VI_VAR_FRAME( VI_INFO_HIST_C_PERIOD ),


	DEF_VI_VAR_FRAME(VI_INFO_HIST_FLAG_IMIN),

	DEF_VI_VAR_FRAME( VI_INFO_VIEW_HIST ),
	DEF_VI_VAR_FRAME( VI_INFO_TOOLTIPS_MODE ),

	DEF_VI_VAR_FRAME( VI_INFO_DEFAULTS ),
	DEF_VI_VAR_FRAME( VI_INFO_DEFAULT_MICRO ),
	DEF_VI_VAR_FRAME( VI_INFO_DEFAULT_MACRO ),
	DEF_VI_VAR_FRAME( VI_INFO_DEFAULT_LD ),

	DEF_VI_VAR_FRAME( VI_INFO_PATH_DB ),
	DEF_VI_VAR_FRAME(VI_INFO_CAMERA_LOCK ),

	DEF_VI_VAR_FRAME( VI_INFO_USER_CURRENT_STR ),
	DEF_VI_VAR_FRAME(VI_INFO_USER_NEW),

	DEF_VI_VAR_FRAME( VI_INFO_TIME_VIDEO_LEN),
	DEF_VI_VAR_FRAME(VI_INFO_TIME_VIDEO_POS),
	DEF_VI_VAR_FRAME(VI_INFO_TIME_VIDEO_STATE),
	DEF_VI_VAR_FRAME( VI_INFO_TIME_VIDEO ),
	DEF_VI_VAR_FRAME( VI_INFO_TIME_AUDIO ),

	DEF_VI_VAR_FRAME( VI_INFO_AVI_TMAX ),
	DEF_VI_VAR_FRAME( VI_INFO_AVI_PURGE ),

	DEF_VI_VAR_FRAME( VI_INFO_AVI_CURRENT_NAME ),

	DEF_VI_VAR_FRAME( VI_INFO_ENGINE_MSND ),
	DEF_VI_VAR_FRAME( VI_INFO_ENGINE_RSND ),

	DEF_VI_VAR_FRAME(VI_INFO_ALERT_SND_PATH),
	DEF_VI_VAR_FRAME( VI_INFO_ALERT_SUSP_SND ),
	DEF_VI_VAR_FRAME( VI_INFO_ALERT_A_SND ),
	DEF_VI_VAR_FRAME( VI_INFO_ALERT_S_SND ),
	DEF_VI_VAR_FRAME( VI_INFO_ALERT_T_SND ),

	DEF_VI_VAR_FRAME( VI_INFO_SOUND_MODE ),
	DEF_VI_VAR_FRAME( VI_INFO_SOUND_KILL ),

	DEF_VI_VAR_FRAME( VI_INFO_CAPTURE_TIMER ),
	DEF_VI_VAR_FRAME( VI_INFO_CAPTURE_TIMER_STOP_IN ),
	DEF_VI_VAR_FRAME( VI_INFO_CAPTURE_TIMER_STOP_AT ),
	DEF_VI_VAR_FRAME( VI_INFO_CAPTURE_TIMER_START_AT ),

	DEF_VI_VAR_FRAME( VI_INFO_CAPTURE_EXTRA_SRC ),
	DEF_VI_VAR_FRAME( VI_INFO_CAPTURE_EXTRA ),
	DEF_VI_VAR_FRAME( VI_INFO_CAPTURE_XML ),
	DEF_VI_VAR_FRAME( VI_INFO_CAPTURE_TXT ),
	DEF_VI_VAR_FRAME( VI_INFO_CAPTURE_DTF ),
	DEF_VI_VAR_FRAME( VI_INFO_CAPTURE_LD ),
	DEF_VI_VAR_FRAME( VI_INFO_CAPTURE_HTTP ),
	DEF_VI_VAR_FRAME( VI_INFO_CAPTURE_IS ),
	DEF_VI_VAR_FRAME( VI_INFO_CAPTURE_COM ),

	DEF_VI_VAR_FRAME( VI_INFO_IMG_REPL ),

	DEF_VI_VAR_FRAME( VI_INFO_AUTO_MARKERS_RQ ),
	DEF_VI_VAR_FRAME( VI_INFO_AUTO_MARKERS_CQ ),
	DEF_VI_VAR_FRAME( VI_INFO_AUTO_MARKERS_SET ),
	
	DEF_VI_VAR_FRAME(VI_INFO_AI_LIVE),
	DEF_VI_VAR_FRAME(VI_INFO_AI_LIVE_TH),
	DEF_VI_VAR_FRAME(VI_INFO_AI_MODE),
	DEF_VI_VAR_FRAME(VI_INFO_SMART_MEASURE),
	DEF_VI_VAR_FRAME( VI_INFO_AUTO_CAPTURE ),
	DEF_VI_VAR_FRAME(VI_INFO_LDQ_MIX),

	DEF_VI_VAR_FRAME(VI_INFO_CAPTURE_LOG),
	DEF_VI_VAR_FRAME( VI_INFO_CAPTURE_MODE ),
	DEF_VI_VAR_FRAME(VI_INFO_VIDEO_ROTATE),
	DEF_VI_VAR_FRAME( VI_INFO_VI_DEVICE ),
	DEF_VI_VAR_FRAME( VI_INFO_VI_DEVICE_INDICATION ),

	DEF_VI_VAR_FRAME( VI_INFO_IMAGE_AUTO ),
	DEF_VI_VAR_FRAME(VI_INFO_IMAGE_AUTO_TIME),
	DEF_VI_VAR_FRAME(VI_INFO_IMAGE_AUTO_FILE),
	DEF_VI_VAR_FRAME(VI_INFO_IMAGE_AUTO_FILE_XML),
	DEF_VI_VAR_FRAME(VI_INFO_IMAGE_AUTO_FACE),
	DEF_VI_VAR_FRAME(VI_INFO_IMAGE_AUTO_ORIGINAL),
	DEF_VI_VAR_FRAME(VI_INFO_IMAGE_AUTO_FACE_VALIDATE),
	DEF_VI_VAR_FRAME(VI_INFO_IMAGE_AUTO_PRINT),
	DEF_VI_VAR_FRAME(VI_INFO_IMAGE_AUTO_GROUP_BY),

	DEF_VI_VAR_FRAME( VI_INFO_IMAGE_COUNT ),
	DEF_VI_VAR_FRAME( VI_INFO_IMAGE_AUTO_CAPTURE ),
	DEF_VI_VAR_FRAME(VI_INFO_IMAGE_FORMAT ),

	DEF_VI_VAR_FRAME( VI_INFO_FPS_IN ),

	DEF_VI_VAR_FRAME( VI_INFO_EEG_TESTMODE ),

	DEF_VI_VAR_FRAME( VI_INFO_LD_TEXT ),

	DEF_VI_VAR_FRAME( VI_INFO_QTEST ),
	DEF_VI_VAR_FRAME(VI_INFO_QTEST_LEVEL_LIGHT),
	DEF_VI_VAR_FRAME(VI_INFO_QTEST_FPS_MIN),
	DEF_VI_VAR_FRAME(VI_INFO_QTEST_FPS_MAX),
	DEF_VI_VAR_FRAME(VI_INFO_QTEST_FACE_DELAY),

	DEF_VI_VAR_FRAME(VI_INFO_MEASURE_FAST),

	DEF_VI_VAR_FRAME(VI_INFO_TVIDEO),
	DEF_VI_VAR_FRAME(VI_INFO_TAUDIO),

	DEF_VI_VAR_FRAME(VI_INFO_CHQ_TEST_RESET),
	DEF_VI_VAR_FRAME(VI_INFO_CHQ_TEST_VALUE),
	DEF_VI_VAR_FRAME(VI_INFO_CHQ_TEST_TYPE),
	DEF_VI_VAR_FRAME(VI_INFO_CHQ_TEST_QUALITY),
	DEF_VI_VAR_FRAME(VI_INFO_CHQ_TEST_ENABLED),

	DEF_VI_VAR_FRAME(VI_INFO_NEED_LOGIN),
	DEF_VI_VAR_FRAME(VI_INFO_SITE_LOGIN),
	DEF_VI_VAR_FRAME(VI_INFO_SITE_PWD),

	DEF_VI_VAR_FRAME(VI_INFO_WND_HIST),
	DEF_VI_VAR_FRAME(VI_INFO_WND_GRAPHS),
	DEF_VI_VAR_FRAME(VI_INFO_WND_LDW),

	DEF_VI_VAR_FRAME(VI_INFO_MARKER),
	

	DEF_VI_VAR_FRAME(VI_INFO_MENU),

	DEF_VI_VAR_FRAME(VI_INFO_USER_DB),

	DEF_VI_VAR_FRAME(VI_INFO_DB_MODE),
	DEF_VI_VAR_FRAME(VI_INFO_DB_SCANKB),
	DEF_VI_VAR_FRAME(VI_MODE_DB_MANUAL),
	DEF_VI_VAR_FRAME(VI_MODE_DB_KEY_ONLY),

	DEF_VI_VAR_FRAME(VI_NETSTATUS_HOST_IP),
	DEF_VI_VAR_FRAME(VI_NETSTATUS_HOST_N),
	DEF_VI_VAR_FRAME(VI_NETSTATUS_HOST_ENABLED),
	DEF_VI_VAR_FRAME(VI_NETSTATUS_HOST_PORT_TCP),
	DEF_VI_VAR_FRAME(VI_NETSTATUS_HOST_PORT_UDP),

	DEF_VI_VAR_FRAME(VI_NETSTATUS_LOCAL_PORT_TCP),

	DEF_VI_VAR_FRAME(VI_NETSTATUS_ENABLED),

	DEF_VI_VAR_FRAME(VI_NETSTATUS_DIRECT_VIDEO),
	DEF_VI_VAR_FRAME(VI_NETSTATUS_COMPRESSION),
	
	DEF_VI_VAR_FRAME(VI_INFO_EXT_VER),

	DEF_VI_VAR_FRAME(VI_INFO_AVG),
	DEF_VI_VAR_FRAME(VI_INFO_CHECK100),
	DEF_VI_VAR_FRAME(VI_INFO_CLOSE_RQST),
		
	DEF_VI_VAR_FRAME(VI_INFO_START_PWD),
	DEF_VI_VAR_FRAME(VI_INFO_START_PWD1),
	DEF_VI_VAR_FRAME(VI_INFO_START_PWD_OK),

	DEF_VI_VAR_FRAME(VI_INFO_LOCK_PWD),
	DEF_VI_VAR_FRAME(VI_INFO_LOCK_PWD1),
	DEF_VI_VAR_FRAME(VI_INFO_LOCK_PWD_OK),
	DEF_VI_VAR_FRAME(VI_INFO_LOCK_PWD_TIMEOUT),

	DEF_VI_VAR_FRAME(VI_INFO_AI_CFG_RANGE),

	DEF_VI_VAR_FRAME(VI_INFO_AI_CFG_NAME),
	DEF_VI_VAR_FRAME(VI_INFO_AI_P36),
	DEF_VI_VAR_FRAME(VI_INFO_AI_P37),
	DEF_VI_VAR_FRAME(VI_INFO_AI_P38),
	DEF_VI_VAR_FRAME(VI_INFO_AI_P41),

	DEF_VI_VAR_FRAME(VI_INFO_AI_NEURO40),
	DEF_VI_VAR_FRAME(VI_INFO_AI_AVG20),
	DEF_VI_VAR_FRAME(VI_INFO_AI_CONFIG),

	DEF_VI_VAR_FRAME(VI_INFO_SAVE_PHOTO),
	DEF_VI_VAR_FRAME(VI_INFO_MEASURE_XML),

	DEF_VI_VAR_FRAME(VI_INFO_USERINFO),
	DEF_VI_VAR_FRAME(VI_INFO_USERINFO_ID),
	DEF_VI_VAR_FRAME(VI_INFO_USERINFO_NAME),
	DEF_VI_VAR_FRAME(VI_INFO_USERINFO_BD),
	DEF_VI_VAR_FRAME(VI_INFO_USERINFO_GENDER),
	DEF_VI_VAR_FRAME(VI_INFO_USERINFO_AGE),
	DEF_VI_VAR_FRAME(VI_INFO_USERINFO_COMMENTS),


	DEF_VI_VAR_FRAME(VI_INFO_TEST_START),
	DEF_VI_VAR_FRAME(VI_INFO_TEST_MODE),
	DEF_VI_VAR_FRAME(VI_INFO_TEST_BG),
	DEF_VI_VAR_FRAME(VI_INFO_TEST_R),
	DEF_VI_VAR_FRAME(VI_INFO_TEST_X_ACTION),
	DEF_VI_VAR_FRAME(VI_INFO_TEST_X_K),
	DEF_VI_VAR_FRAME(VI_INFO_TEST_X1_D),
	DEF_VI_VAR_FRAME(VI_INFO_TEST_X1_T),
	DEF_VI_VAR_FRAME(VI_INFO_TEST_X1_POW),
	DEF_VI_VAR_FRAME(VI_INFO_TEST_X2_D),
	DEF_VI_VAR_FRAME(VI_INFO_TEST_X2_T),
	DEF_VI_VAR_FRAME(VI_INFO_TEST_X2_POW),
	DEF_VI_VAR_FRAME(VI_INFO_TEST_Y_ACTION),
	DEF_VI_VAR_FRAME(VI_INFO_TEST_Y_K),
	DEF_VI_VAR_FRAME(VI_INFO_TEST_Y1_D),
	DEF_VI_VAR_FRAME(VI_INFO_TEST_Y1_T),
	DEF_VI_VAR_FRAME(VI_INFO_TEST_Y1_POW),
	DEF_VI_VAR_FRAME(VI_INFO_TEST_Y2_D),
	DEF_VI_VAR_FRAME(VI_INFO_TEST_Y2_T),
	DEF_VI_VAR_FRAME(VI_INFO_TEST_Y2_POW),

	DEF_VI_VAR_FRAME(VI_INFO_TEST_A1_Y),
	DEF_VI_VAR_FRAME(VI_INFO_TEST_A1_D),
	DEF_VI_VAR_FRAME(VI_INFO_TEST_A1_T),
	DEF_VI_VAR_FRAME(VI_INFO_TEST_A1_POW),

	DEF_VI_VAR_FRAME(VI_INFO_TEST_C1_D),
	DEF_VI_VAR_FRAME(VI_INFO_TEST_C1_T),
	DEF_VI_VAR_FRAME(VI_INFO_TEST_C1_POW),

		
	DEF_VI_VAR_FRAME(VI_INFO_TEST_END),


	DEF_VI_VAR_FRAME(VI_INFO_END)

	DEF_VI_VAR_FRAME_END
};

DEF_VI_VAR_FRAME_DONE

#undef DEF_VI_VAR_FRAME_ENGINE
#undef DEF_VI_VAR_FRAME
#undef DEF_VI_VAR_FRAME_START
#undef DEF_VI_VAR_FRAME_END
#undef DEF_VI_VAR_FRAME_DONE

#endif