#if !defined __VI_VAR_TAG_H__ || defined VI_VAR_MAKE_TAGS
#undef __VI_VAR_TAG_H__
#define __VI_VAR_TAG_H__

#ifdef VI_VAR_MAKE_TAGS
	#define DEF_VI_VAR_ENGINE static LPWSTR gVI_VAR_TAGS[] =
	#define DEF_VI_VAR(x) _T("") _T(#x) _T("")
#else
	#define DEF_VI_VAR_ENGINE enum VI_VAR_ENGINE
	#define DEF_VI_VAR(x) x
#endif

DEF_VI_VAR_ENGINE
{
	DEF_VI_VAR(VI_VAR_ENGINE_START),
	// Critical
	DEF_VI_VAR( VI_CRITICAL_START ), 

	DEF_VI_VAR( VI_VAR_CFG_INIT ),

	DEF_VI_VAR( VI_VAR_SIZE ),

	DEF_VI_VAR( VI_VAR_K ),
	DEF_VI_VAR( VI_VAR_TH ),

	DEF_VI_VAR( VI_VAR_N0 ),
	DEF_VI_VAR( VI_VAR_N1 ),
	DEF_VI_VAR( VI_VAR_N2 ),

	DEF_VI_VAR( VI_VAR_N0_RQST ),
	DEF_VI_VAR( VI_VAR_N1_RQST ),
	DEF_VI_VAR( VI_VAR_N2_RQST ),

	DEF_VI_VAR(VI_VAR_STOP_RQST),

	DEF_VI_VAR(VI_MODE_CAPTURE),

	DEF_VI_VAR( VI_MODE_RESULT ),
	DEF_VI_VAR( VI_MODE_AURA ),
	DEF_VI_VAR(VI_MODE_B),
	DEF_VI_VAR(VI_MODE_RELAX),

	DEF_VI_VAR( VI_VAR_ROOT_PATH ),

	DEF_VI_VAR(VI_VAR_THERMAL_POS),
	DEF_VI_VAR(VI_VAR_THERMAL_SIZE),

	DEF_VI_VAR(VI_FILTER_START),

	DEF_VI_VAR( VI_FILTER_DELTA_LO ),
	DEF_VI_VAR( VI_FILTER_DELTA_LOF ),
	DEF_VI_VAR( VI_FILTER_DELTA_STRETCH ),
	DEF_VI_VAR( VI_FILTER_DELTA_MSCONT ),
	DEF_VI_VAR( VI_FILTER_SP ),
	DEF_VI_VAR( VI_FILTER_AM ),
	DEF_VI_VAR( VI_FILTER_CT ),
	DEF_VI_VAR(VI_FILTER_BTFAST),
	DEF_VI_VAR( VI_FILTER_MOTION ),
	DEF_VI_VAR( VI_FILTER_MOTION_10X ),
	DEF_VI_VAR( VI_FILTER_MOTION_LEVEL ),
	DEF_VI_VAR( VI_FILTER_MOTION_LEVEL2 ),
	DEF_VI_VAR( VI_FILTER_MOTION_SET ),
	DEF_VI_VAR( VI_FILTER_MOTION_AUTO_RESET ),
	DEF_VI_VAR( VI_FILTER_NSKIP ),
	DEF_VI_VAR( VI_FILTER_HISTNW ),
	DEF_VI_VAR( VI_FILTER_CROP ),
	DEF_VI_VAR( VI_FILTER_CROP_POS ),
	DEF_VI_VAR( VI_FILTER_DISTORTION ),
	DEF_VI_VAR( VI_FILTER_STAB_X ),
	DEF_VI_VAR( VI_FILTER_STAB_Y ),

	DEF_VI_VAR( VI_FILTER_BWT_F6_HI ),
	DEF_VI_VAR( VI_FILTER_BWT_F6_LO ),
	DEF_VI_VAR( VI_FILTER_F6_N ),
	DEF_VI_VAR( VI_FILTER_CAMPOS ),
	DEF_VI_VAR( VI_FILTER_CONTOUR ),
	DEF_VI_VAR(VI_FILTER_GPU),
	DEF_VI_VAR( VI_FILTER_GLOBAL ),

	DEF_VI_VAR(VI_FILTER_FPSDIV),
	DEF_VI_VAR(VI_FILTER_FPSDIV_RQST),
	DEF_VI_VAR(VI_FILTER_FPS2IN),
	DEF_VI_VAR(VI_FILTER_DPT),
	DEF_VI_VAR(VI_FILTER_END),

	DEF_VI_VAR( VI_CRITICAL_END ),
// Free
	DEF_VI_VAR( VI_FREE_START ),

	DEF_VI_VAR(VI_VAR_TFRAME_IN),
	DEF_VI_VAR( VI_VAR_NFRAME ),
	DEF_VI_VAR( VI_VAR_NFRAME_IN ),
	DEF_VI_VAR( VI_VAR_NFRAME_OUTF ),

	DEF_VI_VAR( VI_VAR_FPS_PERIOD ),
	DEF_VI_VAR( VI_VAR_FPS_BUFFER_SIZE ),
	DEF_VI_VAR( VI_VAR_FPSIN ),
	DEF_VI_VAR( VI_VAR_FPSOUTF ),
	DEF_VI_VAR( VI_VAR_FPSOUTR ),

	DEF_VI_VAR( VI_VAR_FPSDROPF ),
	DEF_VI_VAR( VI_VAR_FPSDROPR ),
	DEF_VI_VAR( VI_VAR_FPSMAXF ),
	DEF_VI_VAR( VI_VAR_FPSMAXR ),

	DEF_VI_VAR( VI_VAR_NDROP ),
	DEF_VI_VAR(VI_VAR_MEMORY_USAGE), 

	DEF_VI_VAR( VI_FILTER_PAUSE ),
	DEF_VI_VAR( VI_FILTER_SKIP ),

	DEF_VI_VAR(VI_MODE_MEASURE),
	DEF_VI_VAR(VI_MODE_MASK_EDIT),

	DEF_VI_VAR( VI_VAR_AUDIO_DELAY ),
	DEF_VI_VAR( VI_VAR_AUDIO_TH ),
	DEF_VI_VAR( VI_VAR_AUDIO_PERIOD ),

	DEF_VI_VAR( VI_VAR_RESET ),

	DEF_VI_VAR( VI_MODE_WBG ),
	DEF_VI_VAR( VI_MODE_COLOR ),
	DEF_VI_VAR(VI_MODE_AI_DRAW),

	DEF_VI_VAR( VI_VIRTUAL_POS_ENABLE ),
	DEF_VI_VAR( VI_VIRTUAL_POS_INTEGR_LEVEL ),
	DEF_VI_VAR( VI_VIRTUAL_POS_POS ),
	DEF_VI_VAR( VI_VIRTUAL_POS_POS_LOCAL ),
	DEF_VI_VAR( VI_VIRTUAL_POS_SIZE ),

	DEF_VI_VAR(VI_VAR_TEST_MODE),

	DEF_VI_VAR( VI_MACRO_ENABLE ),
	DEF_VI_VAR( VI_MACRO_LEVEL_L ),
	DEF_VI_VAR( VI_MACRO_LEVEL_S ),
	DEF_VI_VAR( VI_MACRO_AURA ),
	DEF_VI_VAR( VI_MACRO_FACE ),

	DEF_VI_VAR(VI_VAR_GROUP_BASE),
	DEF_VI_VAR( VI_FREE_END ),

// disable

	DEF_VI_VAR( VI_FILTER_DISABLE_START ),

	DEF_VI_VAR( VI_FILTER_DISABLE_A ),
	DEF_VI_VAR( VI_FILTER_DISABLE_B ),

	DEF_VI_VAR(VI_FILTER_DISABLE_PROCF),
	DEF_VI_VAR( VI_FILTER_DISABLE_2X ),
	DEF_VI_VAR( VI_FILTER_DISABLE_VI0 ),
	DEF_VI_VAR( VI_FILTER_DISABLE_VI1 ),
	DEF_VI_VAR( VI_FILTER_DISABLE_VI2 ),
	DEF_VI_VAR( VI_FILTER_DISABLE_FFT_UNUSED ),
	DEF_VI_VAR( VI_FILTER_DISABLE_ENTR ),
	DEF_VI_VAR( VI_FILTER_DISABLE_AUDIO ),
	DEF_VI_VAR( VI_FILTER_AUTODOWNRATE ),
	DEF_VI_VAR(VI_FILTER_DISABLE_P7),
	DEF_VI_VAR(VI_FILTER_DISABLE_P6),
	DEF_VI_VAR(VI_FILTER_DISABLE_F5X),
	DEF_VI_VAR(VI_FILTER_DISABLE_STATE),
	DEF_VI_VAR( VI_FILTER_DISABLE_END ),



// LD
	DEF_VI_VAR( VI_VAR_LD_PERIOD ),
	DEF_VI_VAR( VI_VAR_LD_PERIOD_BASE ),
	DEF_VI_VAR( VI_VAR_LD_ENABLE ),
	DEF_VI_VAR( VI_VAR_LD_LTH ),
	DEF_VI_VAR( VI_VAR_LD_MODE ),
	DEF_VI_VAR( VI_VAR_LD_MODE_OPPOSITE ),
	DEF_VI_VAR( VI_VAR_LD_MODE_CMP ),
	DEF_VI_VAR( VI_VAR_LD_STARTED ),
	DEF_VI_VAR(VI_VAR_LD_RESULT),

// hist
	DEF_VI_VAR( VI_VAR_HIST_N_A0 ),
	DEF_VI_VAR( VI_VAR_HIST_N_B0 ),
	DEF_VI_VAR( VI_VAR_HIST_N_A1 ),
	DEF_VI_VAR( VI_VAR_HIST_N_B1 ),
	DEF_VI_VAR( VI_VAR_HIST_N_A2 ),
	DEF_VI_VAR( VI_VAR_HIST_N_B2 ),

	DEF_VI_VAR( VI_VAR_HIST_C_A0_FFTP ),
	DEF_VI_VAR( VI_VAR_HIST_C_A0 ),
	DEF_VI_VAR( VI_VAR_HIST_C_B0 ),
	DEF_VI_VAR( VI_VAR_HIST_C_A1 ),
	DEF_VI_VAR( VI_VAR_HIST_C_B1 ),
	DEF_VI_VAR( VI_VAR_HIST_C_A2 ),
	DEF_VI_VAR( VI_VAR_HIST_C_B2 ),

	DEF_VI_VAR( VI_VAR_HIST_F_A0 ),
	DEF_VI_VAR( VI_VAR_HIST_F_B0 ),
	DEF_VI_VAR( VI_VAR_HIST_F_A1 ),
	DEF_VI_VAR( VI_VAR_HIST_F_B1 ),
	DEF_VI_VAR( VI_VAR_HIST_F_A2 ),
	DEF_VI_VAR( VI_VAR_HIST_F_B2 ),

	DEF_VI_VAR( VI_VAR_HIST_F6 ),
	DEF_VI_VAR( VI_VAR_HIST_F8 ),
	DEF_VI_VAR( VI_VAR_HIST_N_B0_MAX ),
	DEF_VI_VAR( VI_VAR_HIST_N_B0_M ),
	DEF_VI_VAR( VI_VAR_HIST_N_B0_S ),
	DEF_VI_VAR( VI_VAR_HIST_FFT_READY ),

	DEF_VI_VAR( VI_VAR_HIST_CX_AVG_A0 ),
	DEF_VI_VAR( VI_VAR_HIST_CX_AVG_A1 ),
	DEF_VI_VAR( VI_VAR_HIST_CX_AVG_A2 ),

	DEF_VI_VAR( VI_VAR_HIST_CX_AVG_B0 ),
	DEF_VI_VAR( VI_VAR_HIST_CX_AVG_B1 ),
	DEF_VI_VAR( VI_VAR_HIST_CX_AVG_B2 ),


// State
	DEF_VI_VAR( VI_VAR_STAT_RES_P6_LEVEL ), 
	DEF_VI_VAR( VI_VAR_STAT_RES_P7_LEVEL ), 
	DEF_VI_VAR( VI_VAR_STAT_RES_F5X_LEVEL ), 

		// net status
	DEF_VI_VAR(VI_VAR_STATE_CRITICAL_LEV),
	DEF_VI_VAR(VI_VAR_STATE_CUSTOMER_LEV),
	DEF_VI_VAR(VI_VAR_STATE_CRITICAL_S),
	DEF_VI_VAR(VI_VAR_STATE_CRITICAL_K),

	DEF_VI_VAR(VI_VAR_STATE_FLAG_A),
	DEF_VI_VAR(VI_VAR_STATE_FLAG_P),
	DEF_VI_VAR(VI_VAR_STATE_FLAG_CS),

// Stats
	DEF_VI_VAR( VI_STAT_START ),

	DEF_VI_VAR(VI_VAR_STATE_CRITICAL),
	DEF_VI_VAR(VI_VAR_STATE_VAR_PREV),
	DEF_VI_VAR(VI_VAR_STATE_VAR),
	DEF_VI_VAR(VI_VAR_STATE_VAR_REF),
	DEF_VI_VAR(VI_VAR_STATE_VAR_CURRENT),
	DEF_VI_VAR(VI_VAR_STATE_VAR_SRC),

	DEF_VI_VAR( VI_VAR_STAT_INTEGR2A ),
	DEF_VI_VAR( VI_VAR_STAT_INTEGR1A ),
	DEF_VI_VAR( VI_VAR_STAT_INTEGR0A ),

	DEF_VI_VAR( VI_VAR_STAT_INTEGR2B ),
	DEF_VI_VAR( VI_VAR_STAT_INTEGR1B ),
	DEF_VI_VAR( VI_VAR_STAT_INTEGR0B ),
	DEF_VI_VAR(VI_VAR_STAT_INTEGR0S),

	DEF_VI_VAR( VI_VAR_STAT_RES_A1X  ), // межкадровая разность чистая (2x)

	DEF_VI_VAR( VI_VAR_STAT_RES_A1 ), // межкадровая разность чистая 
	DEF_VI_VAR( VI_VAR_STAT_RES_A2 ), // межкадровая разность внутри контура (10)
	DEF_VI_VAR( VI_VAR_STAT_RES_A3 ), // межкадровая разность внутри контура (N)
	DEF_VI_VAR( VI_VAR_STAT_RES_A4X ), // A1X avg
	DEF_VI_VAR( VI_VAR_STAT_RES_A4 ), // A1 avg

	DEF_VI_VAR( VI_VAR_STAT_RES_F1X ), // межкадровая разность чистая (F) (2x)
	DEF_VI_VAR( VI_VAR_STAT_RES_F1D ), // d межкадровая разность чистая (F) (2x)
	DEF_VI_VAR( VI_VAR_STAT_RES_F1 ), // межкадровая разность чистая (F)
	DEF_VI_VAR( VI_VAR_STAT_RES_F2 ), // межкадровая разность внутри контура (10)
	DEF_VI_VAR( VI_VAR_STAT_RES_F3 ), // межкадровая разность внутри контура (N)
	DEF_VI_VAR( VI_VAR_STAT_RES_F4 ), // maxC
	DEF_VI_VAR( VI_VAR_STAT_RES_F5X ), // hf/lf (2x) // tension
	DEF_VI_VAR( VI_VAR_STAT_RES_F5 ), // hf/lf
	DEF_VI_VAR( VI_VAR_STAT_RES_F6 ), // VI_VAR_STAT_RES_F8 сред по N
	DEF_VI_VAR( VI_VAR_STAT_RES_F7 ), // SKO F6
	DEF_VI_VAR( VI_VAR_STAT_RES_F8 ), // фильтр F1X по частоте (интервалы времени)
	DEF_VI_VAR( VI_VAR_STAT_RES_F9 ), 

	DEF_VI_VAR( VI_VAR_STAT_RES_S1 ), // симмерия 2
	DEF_VI_VAR( VI_VAR_STAT_RES_S2 ), // симмерия 10
	DEF_VI_VAR( VI_VAR_STAT_RES_S3 ), // симмерия N
	DEF_VI_VAR( VI_VAR_STAT_RES_S4 ), // симмерия 2
	DEF_VI_VAR( VI_VAR_STAT_RES_S5 ), // симмерия 10
	DEF_VI_VAR( VI_VAR_STAT_RES_S6 ), // симмерия N
	DEF_VI_VAR( VI_VAR_STAT_RES_S7 ), // симмерия maxC

	DEF_VI_VAR( VI_VAR_STAT_RES_P1 ), // дисперсия част ауры 10
	DEF_VI_VAR( VI_VAR_STAT_RES_P2 ), // дисперсия част ауры N
	DEF_VI_VAR( VI_VAR_STAT_RES_P3 ), // симметрия част ауры 10
	DEF_VI_VAR( VI_VAR_STAT_RES_P4 ), // симметрия част ауры N

	DEF_VI_VAR( VI_VAR_STAT_RES_P5 ), //  Уровень лжи
	DEF_VI_VAR( VI_VAR_STAT_RES_P7A ), //  Anger
	DEF_VI_VAR( VI_VAR_STAT_RES_P6A ), //  Stress
	DEF_VI_VAR( VI_VAR_STAT_RES_P7F ), //  Anger
	DEF_VI_VAR( VI_VAR_STAT_RES_P6F ), //  Stress

	DEF_VI_VAR( VI_VAR_STAT_RES_P8A ), //  energy
	DEF_VI_VAR( VI_VAR_STAT_RES_P8F ), //  energy

	DEF_VI_VAR( VI_VAR_STAT_RES_P9A ), //  энтропия H
	DEF_VI_VAR( VI_VAR_STAT_RES_P9F ), //  энтропия H

	DEF_VI_VAR( VI_VAR_STAT_RES_P10A ), //  энтропия D
	DEF_VI_VAR( VI_VAR_STAT_RES_P10F ), //  энтропия D

	DEF_VI_VAR( VI_VAR_STAT_RES_P11A ), //  энтропия X
	DEF_VI_VAR( VI_VAR_STAT_RES_P11F ), //  энтропия X

	DEF_VI_VAR( VI_VAR_STAT_RES_P12A ), //  энтропия S
	DEF_VI_VAR( VI_VAR_STAT_RES_P12F ), //  энтропия S

	DEF_VI_VAR( VI_VAR_STAT_RES_P13 ), //  (F-L)/(Fm-L) (macro)
	DEF_VI_VAR( VI_VAR_STAT_RES_P14 ), //  (N-Nn)/N (macro)
	DEF_VI_VAR( VI_VAR_STAT_RES_P15 ), //  100.0*N/wh (macro)

	DEF_VI_VAR( VI_VAR_STAT_RES_P16 ), //  CN (ComN)
	DEF_VI_VAR( VI_VAR_STAT_RES_P17 ), // CS (ComS) charming
	DEF_VI_VAR( VI_VAR_STAT_RES_P18 ), // Com = (CN+CS)/2

	DEF_VI_VAR( VI_VAR_STAT_RES_P19 ), // VI_VAR_STATE_VAR

	DEF_VI_VAR( VI_VAR_STAT_RES_P20 ), //  Уровень лжи #2

	DEF_VI_VAR( VI_VAR_STAT_RES_P21 ), //  Здоровье (расчетный) по 3
	DEF_VI_VAR( VI_VAR_STAT_RES_P22 ), //  Здоровье (расчетный) по 10
	DEF_VI_VAR( VI_VAR_STAT_RES_P23 ), //  К-т вариабельности (расчетный) по 10
	DEF_VI_VAR( VI_VAR_STAT_RES_P24 ), //  К-т Сонливости V/S(p17)
	DEF_VI_VAR( VI_VAR_STAT_RES_P25 ), //  К-т Сонливости V(p17)

	DEF_VI_VAR( VI_VAR_STAT_RES_P26 ), //  экстраверсия
	DEF_VI_VAR( VI_VAR_STAT_RES_P27 ), //  Интроверсия

	DEF_VI_VAR( VI_VAR_STAT_RES_P28 ), //  К-т Сонливости

	DEF_VI_VAR(VI_VAR_STAT_RES_P29), //  Депрессия
	DEF_VI_VAR(VI_VAR_STAT_RES_P30), //  Счастье

	DEF_VI_VAR(VI_VAR_STAT_RES_P31), //  Контраст лица
	DEF_VI_VAR(VI_VAR_STAT_RES_P32), //  Перекос яркости лица
	DEF_VI_VAR(VI_VAR_STAT_RES_P33), //  Chq type
	DEF_VI_VAR(VI_VAR_STAT_RES_P34), //  Chq value
	DEF_VI_VAR(VI_VAR_STAT_RES_P35), //  Satisfaction

	DEF_VI_VAR(VI_VAR_STAT_RES_P36), //  AI Ht 
	DEF_VI_VAR(VI_VAR_STAT_RES_P37), //  AI Live 
	DEF_VI_VAR(VI_VAR_STAT_RES_P38), //  AI Result 
	DEF_VI_VAR(VI_VAR_STAT_RES_P39), //  AI Result Timer
	DEF_VI_VAR(VI_VAR_STAT_RES_P40), //  AI Result Timer Max
	DEF_VI_VAR(VI_VAR_STAT_RES_P41), //  AI Current value
	DEF_VI_VAR(VI_VAR_STAT_RES_P42), //  AI Threshold
	DEF_VI_VAR(VI_VAR_STAT_RES_P43), //  Thermal t
	DEF_VI_VAR(VI_VAR_STAT_RES_P44), //  Thermal t Min
	DEF_VI_VAR(VI_VAR_STAT_RES_P45), //  Thermal t Max
	DEF_VI_VAR(VI_VAR_STAT_RES_P46), //  Thermal t S



	DEF_VI_VAR(VI_VAR_STAT_RES_HRA_128), //  PulseHR A
	DEF_VI_VAR(VI_VAR_STAT_RES_HRF_128), //  PulseHR F
	DEF_VI_VAR(VI_VAR_STAT_RES_HRA_256), //  PulseHR A
	DEF_VI_VAR(VI_VAR_STAT_RES_HRF_256), //  PulseHR F
	DEF_VI_VAR(VI_VAR_STAT_RES_HRA_512), //  PulseHR A
	DEF_VI_VAR(VI_VAR_STAT_RES_HRF_512), //  PulseHR F
	DEF_VI_VAR(VI_VAR_STAT_RES_HRA_1024), //  PulseHR A
	DEF_VI_VAR(VI_VAR_STAT_RES_HRF_1024), //  PulseHR F

	DEF_VI_VAR(VI_VAR_STAT_RES_HT),   //  HT  value
	DEF_VI_VAR(VI_VAR_STAT_RES_HTMV), //  HT refM value
	DEF_VI_VAR(VI_VAR_STAT_RES_HTCV), //  HT Cor  value
	DEF_VI_VAR(VI_VAR_STAT_RES_HTMT), //  HT refM Treshold
	DEF_VI_VAR(VI_VAR_STAT_RES_HTCT), //  HT Cor  Treshold

	DEF_VI_VAR( VI_VAR_STAT_RES_SIN ), //  Sin

	DEF_VI_VAR( VI_VAR_STAT_RES_C1 ), //  
	DEF_VI_VAR( VI_VAR_STAT_RES_C1X ), //  
	DEF_VI_VAR( VI_VAR_STAT_RES_C2 ), //  
	DEF_VI_VAR( VI_VAR_STAT_RES_C2X ), //  
	DEF_VI_VAR( VI_VAR_STAT_RES_C3 ), //  
	DEF_VI_VAR( VI_VAR_STAT_RES_C4 ), //  

	DEF_VI_VAR( VI_VAR_STAT_RES_FN01 ), //  fn1
	DEF_VI_VAR( VI_VAR_STAT_RES_FN02 ), //  fn2
	DEF_VI_VAR( VI_VAR_STAT_RES_FN03 ), //  fn3
	DEF_VI_VAR( VI_VAR_STAT_RES_FN04 ), //  fn4
	DEF_VI_VAR( VI_VAR_STAT_RES_FN05 ), //  fn5
	DEF_VI_VAR( VI_VAR_STAT_RES_FN06 ), //  fn6
	DEF_VI_VAR( VI_VAR_STAT_RES_FN07 ), //  fn7
	DEF_VI_VAR( VI_VAR_STAT_RES_FN08 ), //  fn8
	DEF_VI_VAR( VI_VAR_STAT_RES_FN09 ), //  fn9
	DEF_VI_VAR( VI_VAR_STAT_RES_FN10 ), //  fn10

	DEF_VI_VAR(VI_VAR_STAT_RES_II1),
	DEF_VI_VAR(VI_VAR_STAT_RES_II2),
	DEF_VI_VAR(VI_VAR_STAT_RES_IE1),
	DEF_VI_VAR(VI_VAR_STAT_RES_IE2),
	DEF_VI_VAR(VI_VAR_STAT_RES_II),
	DEF_VI_VAR(VI_VAR_STAT_RES_IE),
	DEF_VI_VAR(VI_VAR_STAT_RES_IP),
	DEF_VI_VAR(VI_VAR_STAT_RES_IPM),
	DEF_VI_VAR(VI_VAR_STAT_RES_SAT),
	DEF_VI_VAR(VI_VAR_STAT_RES_DP5), // dP (5s sin, min max)

	DEF_VI_VAR( VI_STAT_END ),

	DEF_VI_VAR( VI_STAT_EXT_START ),
// stat add
	DEF_VI_VAR( VI_VAR_STAT_RES_P6 ), //  Stress (задается извне)
	DEF_VI_VAR( VI_VAR_STAT_RES_P7 ), //  Anger (задается извне)
	DEF_VI_VAR( VI_VAR_STAT_RES_P8 ), //  energy (задается извне)
	DEF_VI_VAR( VI_VAR_STAT_RES_P9 ), //  энтропия H (задается извне)
	DEF_VI_VAR( VI_VAR_STAT_RES_P10 ), //  энтропия D (задается извне)
	DEF_VI_VAR( VI_VAR_STAT_RES_P11 ), //  энтропия X (задается извне)
	DEF_VI_VAR( VI_VAR_STAT_RES_P12 ), //  энтропия S (задается извне)

	DEF_VI_VAR( VI_STAT_EXT_END ),

	DEF_VI_VAR( VI_STAT_EXTR_START ),
// pulse
	DEF_VI_VAR( VI_VAR_STAT_PULSE_START ),

	DEF_VI_VAR( VI_VAR_STAT_PULSE_AVGALL ),
	DEF_VI_VAR( VI_VAR_STAT_PULSE_SIGMAALL ),

	DEF_VI_VAR( VI_VAR_STAT_PULSE_AVGZONE ),
	DEF_VI_VAR( VI_VAR_STAT_PULSE_SIGMAZONE ),

	DEF_VI_VAR( VI_VAR_STAT_PULSE_AVGZONE2 ),
	DEF_VI_VAR( VI_VAR_STAT_PULSE_SIGMAZONE2 ),

	DEF_VI_VAR( VI_VAR_STAT_PULSE_AVGLINE1 ),
	DEF_VI_VAR( VI_VAR_STAT_PULSE_SIGMALINE1 ),

	DEF_VI_VAR( VI_VAR_STAT_PULSE_AVGLINE2 ),
	DEF_VI_VAR( VI_VAR_STAT_PULSE_SIGMALINE2 ),

	DEF_VI_VAR( VI_VAR_STAT_PULSE_AVGLINE3 ),
	DEF_VI_VAR( VI_VAR_STAT_PULSE_SIGMALINE3 ),

	DEF_VI_VAR( VI_VAR_STAT_PULSE_SIN ),

	DEF_VI_VAR( VI_VAR_STAT_PULSE_PHASE_T ),
	DEF_VI_VAR( VI_VAR_STAT_PULSE_PHASE_A ),
	DEF_VI_VAR( VI_VAR_STAT_PULSE_PULSE10 ),

	DEF_VI_VAR( VI_VAR_STAT_PULSE_AVGX0 ),
	DEF_VI_VAR( VI_VAR_STAT_PULSE_AVGX1 ),
	DEF_VI_VAR( VI_VAR_STAT_PULSE_AVGX2 ),
	DEF_VI_VAR( VI_VAR_STAT_PULSE_AVGX3 ),
	DEF_VI_VAR( VI_VAR_STAT_PULSE_AVGX4 ),
	DEF_VI_VAR( VI_VAR_STAT_PULSE_AVGX5 ),
	DEF_VI_VAR( VI_VAR_STAT_PULSE_AVGX6 ),
	DEF_VI_VAR( VI_VAR_STAT_PULSE_AVGX7 ),
	DEF_VI_VAR( VI_VAR_STAT_PULSE_AVGX8 ),
	DEF_VI_VAR( VI_VAR_STAT_PULSE_AVGX9 ),
	DEF_VI_VAR( VI_VAR_STAT_PULSE_SIGMAX0 ),
	DEF_VI_VAR( VI_VAR_STAT_PULSE_SIGMAX1 ),
	DEF_VI_VAR( VI_VAR_STAT_PULSE_SIGMAX2 ),
	DEF_VI_VAR( VI_VAR_STAT_PULSE_SIGMAX3 ),
	DEF_VI_VAR( VI_VAR_STAT_PULSE_SIGMAX4 ),
	DEF_VI_VAR( VI_VAR_STAT_PULSE_SIGMAX5 ),
	DEF_VI_VAR( VI_VAR_STAT_PULSE_SIGMAX6 ),
	DEF_VI_VAR( VI_VAR_STAT_PULSE_SIGMAX7 ),
	DEF_VI_VAR( VI_VAR_STAT_PULSE_SIGMAX8 ),
	DEF_VI_VAR( VI_VAR_STAT_PULSE_SIGMAX9 ),

	DEF_VI_VAR( VI_VAR_STAT_PULSE_END ),

// eeg
	DEF_VI_VAR( VI_VAR_STAT_ANDROID_START ),

	DEF_VI_VAR( VI_VAR_STAT_ANDROID00 ),
	DEF_VI_VAR( VI_VAR_STAT_ANDROID01 ),
	DEF_VI_VAR( VI_VAR_STAT_ANDROID02 ),
	DEF_VI_VAR( VI_VAR_STAT_ANDROID03 ),
	DEF_VI_VAR( VI_VAR_STAT_ANDROID04 ),
	DEF_VI_VAR( VI_VAR_STAT_ANDROID05 ),
	DEF_VI_VAR( VI_VAR_STAT_ANDROID06 ),
	DEF_VI_VAR( VI_VAR_STAT_ANDROID07 ),
	DEF_VI_VAR( VI_VAR_STAT_ANDROID08 ),
	DEF_VI_VAR( VI_VAR_STAT_ANDROID09 ),
	DEF_VI_VAR( VI_VAR_STAT_ANDROID10 ),
	DEF_VI_VAR( VI_VAR_STAT_ANDROID11 ),
	DEF_VI_VAR( VI_VAR_STAT_ANDROID12 ),
	DEF_VI_VAR( VI_VAR_STAT_ANDROID13 ),
	DEF_VI_VAR( VI_VAR_STAT_ANDROID14 ),
	DEF_VI_VAR( VI_VAR_STAT_ANDROID15 ),
	DEF_VI_VAR( VI_VAR_STAT_ANDROID16 ),
	DEF_VI_VAR( VI_VAR_STAT_ANDROID17 ),
	DEF_VI_VAR( VI_VAR_STAT_ANDROID18 ),
	DEF_VI_VAR( VI_VAR_STAT_ANDROID19 ),
	DEF_VI_VAR( VI_VAR_STAT_ANDROID20 ),
	DEF_VI_VAR( VI_VAR_STAT_ANDROID21 ),
	DEF_VI_VAR( VI_VAR_STAT_ANDROID22 ),
	DEF_VI_VAR( VI_VAR_STAT_ANDROID23 ),
	DEF_VI_VAR( VI_VAR_STAT_ANDROID24 ),
	DEF_VI_VAR( VI_VAR_STAT_ANDROID25 ),
	DEF_VI_VAR( VI_VAR_STAT_ANDROID26 ),
	DEF_VI_VAR( VI_VAR_STAT_ANDROID27 ),
	DEF_VI_VAR( VI_VAR_STAT_ANDROID28 ),
	DEF_VI_VAR( VI_VAR_STAT_ANDROID29 ),
	DEF_VI_VAR( VI_VAR_STAT_ANDROID30 ),
	DEF_VI_VAR( VI_VAR_STAT_ANDROID31 ),
	DEF_VI_VAR( VI_VAR_STAT_ANDROID32 ),
	DEF_VI_VAR( VI_VAR_STAT_ANDROID33 ),
	DEF_VI_VAR( VI_VAR_STAT_ANDROID34 ),
	DEF_VI_VAR( VI_VAR_STAT_ANDROID35 ),
	DEF_VI_VAR( VI_VAR_STAT_ANDROID36 ),
	DEF_VI_VAR( VI_VAR_STAT_ANDROID37 ),
	DEF_VI_VAR( VI_VAR_STAT_ANDROID38 ),
	DEF_VI_VAR( VI_VAR_STAT_ANDROID39 ),

	DEF_VI_VAR( VI_VAR_STAT_ANDROID_END ),

// eeg
	DEF_VI_VAR( VI_VAR_STAT_EEG_START ),

	DEF_VI_VAR( VI_VAR_STAT_EEG00 ),
	DEF_VI_VAR( VI_VAR_STAT_EEG01 ),
	DEF_VI_VAR( VI_VAR_STAT_EEG02 ),
	DEF_VI_VAR( VI_VAR_STAT_EEG03 ),
	DEF_VI_VAR( VI_VAR_STAT_EEG04 ),
	DEF_VI_VAR( VI_VAR_STAT_EEG05 ),
	DEF_VI_VAR( VI_VAR_STAT_EEG06 ),
	DEF_VI_VAR( VI_VAR_STAT_EEG07 ),
	DEF_VI_VAR( VI_VAR_STAT_EEG08 ),
	DEF_VI_VAR( VI_VAR_STAT_EEG09 ),
	DEF_VI_VAR( VI_VAR_STAT_EEG10 ),
	DEF_VI_VAR( VI_VAR_STAT_EEG11 ),
	DEF_VI_VAR( VI_VAR_STAT_EEG12 ),
	DEF_VI_VAR( VI_VAR_STAT_EEG13 ),
	DEF_VI_VAR( VI_VAR_STAT_EEG14 ),
	DEF_VI_VAR( VI_VAR_STAT_EEG15 ),
	DEF_VI_VAR( VI_VAR_STAT_EEG16 ),
	DEF_VI_VAR( VI_VAR_STAT_EEG17 ),
	DEF_VI_VAR( VI_VAR_STAT_EEG18 ),
	DEF_VI_VAR( VI_VAR_STAT_EEG19 ),
	DEF_VI_VAR( VI_VAR_STAT_EEG20 ),
	DEF_VI_VAR( VI_VAR_STAT_EEG21 ),
	DEF_VI_VAR( VI_VAR_STAT_EEG22 ),
	DEF_VI_VAR( VI_VAR_STAT_EEG23 ),
	DEF_VI_VAR( VI_VAR_STAT_EEG24 ),
	DEF_VI_VAR( VI_VAR_STAT_EEG25 ),
	DEF_VI_VAR( VI_VAR_STAT_EEG26 ),
	DEF_VI_VAR( VI_VAR_STAT_EEG27 ),
	DEF_VI_VAR( VI_VAR_STAT_EEG28 ),
	DEF_VI_VAR( VI_VAR_STAT_EEG29 ),
	DEF_VI_VAR( VI_VAR_STAT_EEG30 ),
	DEF_VI_VAR( VI_VAR_STAT_EEG31 ),
	DEF_VI_VAR( VI_VAR_STAT_EEG32 ),
	DEF_VI_VAR( VI_VAR_STAT_EEG33 ),
	DEF_VI_VAR( VI_VAR_STAT_EEG34 ),
	DEF_VI_VAR( VI_VAR_STAT_EEG35 ),
	DEF_VI_VAR( VI_VAR_STAT_EEG36 ),
	DEF_VI_VAR( VI_VAR_STAT_EEG37 ),
	DEF_VI_VAR( VI_VAR_STAT_EEG38 ),
	DEF_VI_VAR( VI_VAR_STAT_EEG39 ),

	DEF_VI_VAR( VI_VAR_STAT_EEG_END ),

	DEF_VI_VAR( VI_STAT_EXTR_END ),

//	Correlation
	DEF_VI_VAR(VI_VAR_CORRELATION_VALUE),
	DEF_VI_VAR( VI_VAR_CORRELATION_ENABLE ),
	DEF_VI_VAR( VI_VAR_CORRELATION_MEDIAN ),
	DEF_VI_VAR( VI_VAR_CORRELATION_TSTAT ),
	DEF_VI_VAR( VI_VAR_CORRELATION_TSHIFT1 ),
	DEF_VI_VAR( VI_VAR_CORRELATION_TSHIFT2 ),
	DEF_VI_VAR( VI_VAR_CORRELATION_TAUTO ),
	DEF_VI_VAR(VI_VAR_CORRELATION_SORT),
	DEF_VI_VAR( VI_VAR_CORRELATION_X ),
	DEF_VI_VAR( VI_VAR_CORRELATION_Y ),
	DEF_VI_VAR( VI_VAR_CORRELATION_HIPASS ),
	DEF_VI_VAR( VI_VAR_CORRELATION_LOPASS ),
	DEF_VI_VAR( VI_VAR_CORRELATION_AVG ),
	DEF_VI_VAR( VI_VAR_CORRELATION_MAKE_T ),

// audio stat
	DEF_VI_VAR( VI_VAR_AUDIO_LEVEL ),
	DEF_VI_VAR( VI_VAR_AUDIO_LEVEL25 ),
	DEF_VI_VAR( VI_VAR_AUDIO_SENSITIVITY ),

// face detect
	DEF_VI_VAR( VI_FACE_ENABLE ),
	DEF_VI_VAR( VI_FACE_QUALITY ),
	DEF_VI_VAR( VI_FACE_SCALE ),
	DEF_VI_VAR( VI_FACE_QUALITY_SIZE_MIN ),
	DEF_VI_VAR( VI_FACE_QUALITY_SIZE_MAX ),
	DEF_VI_VAR( VI_FACE_DRAW ),
	DEF_VI_VAR(VI_FACE_MAX),
	DEF_VI_VAR( VI_FACE_INFO ),
	DEF_VI_VAR( VI_FACE_INFO_DETECT ),
	DEF_VI_VAR( VI_FACE_INFO_DETECT_SAVE ),
	DEF_VI_VAR( VI_FACE_PATH ),
	DEF_VI_VAR( VI_FACE_PATH2),
	DEF_VI_VAR(VI_FACE_MODE_SYNC),


// stat cfg
	DEF_VI_VAR( VI_VAR_STAT_CFG_SIN ), //  Sin period
	DEF_VI_VAR( VI_VAR_STAT_CFG_HISTFN ), //  HistFn

// seq
	DEF_VI_VAR( VI_VAR_SEQ_PASSWORD ), 
	DEF_VI_VAR( VI_VAR_SEQ_ANSWER ), 
	DEF_VI_VAR( VI_VAR_SEQ_CODE ), 
	DEF_VI_VAR(VI_VAR_SEQ_MEASURE),
	DEF_VI_VAR(VI_VAR_SEQ_MEASURE_FILE),	
	DEF_VI_VAR(VI_VAR_SEQ_MEASURE_STATUS),
	DEF_VI_VAR(VI_VAR_SEQ_HTTP_STATUS),
	DEF_VI_VAR( VI_VAR_SEQ_INET ), 
	DEF_VI_VAR( VI_VAR_SEQ_MASK ), 
	DEF_VI_VAR( VI_VAR_SEQ_REQUEST ), 
	DEF_VI_VAR(VI_VAR_SEQ_LIMIT_DT),

	DEF_VI_VAR(VI_VAR_CORE_MAX),

	DEF_VI_VAR(VI_VAR_APP_VER),

// total
	DEF_VI_VAR( VI_VAR_CNT),
	DEF_VI_VAR(VI_VAR_ENGINE_END)
};

#undef DEF_VI_VAR_ENGINE
#undef DEF_VI_VAR

#endif