//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by VibraimageEx.rc
//
#define ID_SEPARATOR                    0
#define VS_VERSION_INFO                 1
#define IDC_BTN_GET_AUTHCODE_HTTP       3
#define AFX_IDC_LISTBOX                 100
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define AFX_IDC_CHANGE                  101
#define IDS_ERROR_AVX                   101
#define AFX_IDC_BROWSER                 102
#define IDS_ERROR_SSE                   102
#define IDS_ERROR_EXCEL                 103
#define IDP_SOCKETS_INIT_FAILED         104
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDS_TOOLBAR_STANDARD            124
#define IDS_TOOLBAR_CUSTOMIZE           125
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define ID_VIEW_FILEVIEW                133
#define ID_VIEW_CLASSVIEW               134
#define ID_PROPERTIES                   135
#define ID_OPEN                         136
#define ID_OPEN_WITH                    137
#define ID_DUMMY_COMPILE                138
#define ID_CLASS_ADD_MEMBER_FUNCTION    139
#define ID_CLASS_ADD_MEMBER_VARIABLE    140
#define ID_CLASS_DEFINITION             141
#define ID_CLASS_PROPERTIES             142
#define ID_NEW_FOLDER                   143
#define ID_SORT_MENU                    144
#define ID_SORTING_GROUPBYTYPE          145
#define ID_SORTING_SORTALPHABETIC       146
#define ID_SORTING_SORTBYTYPE           147
#define ID_SORTING_SORTBYACCESS         148
#define ID_VIEW_PROPERTIESWND           150
#define ID_SORTPROPERTIES               151
#define ID_PROPERTIES1                  152
#define ID_PROPERTIES2                  153
#define ID_EXPAND_ALL                   154
#define IDS_FILE_VIEW                   155
#define IDS_CLASS_VIEW                  156
#define IDS_PROPERTIES_WND              158
#define IDD_DIALOG_INETKEY              159
#define IDD_DIALOG_PROGRESS             166
#define IDR_EXPLORER                    169
#define IDR_SORT                        171
#define IDR_POPUP_SORT                  173
#define IDR_POPUP_EXPLORER              174
#define IDD_DGBAR_LD_LITE               174
#define IDR_PROPERTIES                  183
#define IDR_THEME_MENU                  200
#define ID_SET_STYLE                    201
#define IDS_EXPLORER                    305
#define IDS_EDIT_MENU                   306
#define IDR_MENU_TMP                    310
#define IDD_DIALOG1                     321
#define IDD_DIALOG_ID                   321
#define IDD_DIALOG_PWD                  330
#define IDD_DIALOG_PWD2                 332
#define IDD_DIALOG_INETKEY_SIMPLE       333
#define IDD_DIALOG2                     336
#define IDD_HT_RESULT_HTML              336
#define IDD_DIALOG_STARTER              338
#define IDD_DIALOG_LOGIN                342
#define IDI_ICON1                       343
#define IDC_ABOUT1                      1000
#define IDC_PROGRESS1                   1001
#define IDC_ABOUT2                      1001
#define IDC_ABOUT3                      1002
#define IDC_BUTTON_UNREGISTER           1003
#define IDC_ABOUT0                      1004
#define IDC_STATIC_COPYRIGHT            1005
#define IDC_EDIT1                       1006
#define IDC_EDIT_ID                     1006
#define IDC_EDIT_PWD                    1006
#define IDC_STATIC_PWD1                 1008
#define IDC_EDIT_PWD2                   1009
#define IDC_BUTTON1                     1009
#define IDC_BUTTON_WEB                  1009
#define IDC_STATIC_PWD2                 1010
#define IDC_STATIC_CODE                 1012
#define IDC_STATIC_ANSWER               1013
#define IDC_EDIT_PWD3                   1013
#define IDC_EDIT_CODE                   1014
#define IDC_STATIC_PWD3                 1014
#define IDC_EDIT_ANSWER                 1015
#define IDC_STATIC_REQUEST              1016
#define IDC_EDIT_REQUEST                1017
#define IDC_BUTTON_DEMO                 1028
#define ID_SETTINGS_LOCK                1029
#define IDC_EDIT_LOGIN                  1030
#define IDC_EDIT_PASSWORD               1031
#define IDC_LOGIN_TXT                   1032
#define IDC_PASSWORD_TXT                1033
#define IDC_CHECK_REMEMBER              1034
#define IDC_CHECK1                      1036
#define ID_COMMAND_REG                  32771
#define ID_COMMAND_REG_SAVE             32772
#define ID_SETTINGS_LANGUAGE            32811
#define ID_COMMAND_CROPCENTER           32826
#define ID_PANE_VIEW                    32828
#define ID_VIEW_AV                      32829
#define ID_VIEW_LDBAR                   32847
#define IDC_BUTTON_SCAN                 32848
#define ID_LD_AUDIO                     32849
#define ID_LD_MANUAL                    32850
#define ID_LD_AUTO                      32851
#define ID_BUTTON_LD                    32852
#define ID_COMMAND_UPDATELANG           32854
#define ID_COMMAND_REMOVEHIST           32855
#define ID_COMMAND_START                32856
#define ID_COMMAND_STOP                 32857
#define ID_COMMAND_L                    32858
#define ID_COMMAND_LITELDRESULT         32859
#define ID_COMMAND_MENU                 32860
#define ID_COMMAND_ENABLEINPUT          32861
#define ID_COMMAND_UPDATEALL            32862
#define ID_COMMAND_OPENARCHIVEFOLDER    32863
#define ID_COMMAND_LITELOG              32864
#define ID_PANE_TABTOVIEW               32865
#define ID_VIEW_SIMPLE                  32866
#define ID_VIEW_SIMPLE32868             32868
#define ID_COMMAND_CHECKID              32871
#define ID_SETTINGS_ENABLE              32878

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        344
#define _APS_NEXT_COMMAND_VALUE         32881
#define _APS_NEXT_CONTROL_VALUE         1037
#define _APS_NEXT_SYMED_VALUE           311
#endif
#endif
